INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Big Buddy Bike", "Design and Tech", 80000, "2018-01-08", "2018-04-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Deadwood 1876", "Tabletop Games", 25000, "2018-02-03", "2018-03-22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pugs Unleashed!", "Webcomics", 25000, "2017-12-18", "2018-03-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Aurga", "Camera Equipment", 20000, "2018-01-01", "2018-03-07");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pulp Detective", "Tabletop Games", 7000, "2018-02-01", "2018-02-28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("INFERNO", "Comics", 10000, "2017-11-30", "2018-03-07");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Subatomic", "Tabletop Games", 12500, "2018-01-05", "2018-03-08");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("CrazyEightyEight", "Rock", 50000, "2017-11-29", "2018-02-28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("A new Erick Sermon album", "Music", 60000, "2017-11-01", "2018-02-22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The 826 New Orleans Youth Publication Center", "Publishing", 20000, "2018-01-04", "2018-03-22");
INSERT INTO users (name, age) VALUES ("Rhiannon", 33);
INSERT INTO users (name, age) VALUES ("Patti", 54);
INSERT INTO users (name, age) VALUES ("Curt", 56);
INSERT INTO users (name, age) VALUES ("Brennan", 20);
INSERT INTO users (name, age) VALUES ("Adelyn", 27);
INSERT INTO users (name, age) VALUES ("Patricia", 77);
INSERT INTO users (name, age) VALUES ("Bob", 58);
INSERT INTO users (name, age) VALUES ("Pete", 53);
INSERT INTO users (name, age) VALUES ("Danielle", 36);
INSERT INTO users (name, age) VALUES ("Jennifer", 36);
INSERT INTO users (name, age) VALUES ("Jolene", 36);
INSERT INTO users (name, age) VALUES ("Kate", 35);
INSERT INTO users (name, age) VALUES ("John", 45);
INSERT INTO users (name, age) VALUES ("Paul", 70);
INSERT INTO users (name, age) VALUES ("George", 63);
INSERT INTO users (name, age) VALUES ("Ringo", 70);
INSERT INTO users (name, age) VALUES ("David", 58);
INSERT INTO users (name, age) VALUES ("Les", 78);
INSERT INTO users (name, age) VALUES ("Ian", 23);
INSERT INTO users (name, age) VALUES ("Josephine", 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 18, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (222.22, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (330.50, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000.11, 17, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1700.49, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (299.99, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (450, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (329.99, 11, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (217.89, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (249.89, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (309.89, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (325, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1200, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1600, 16, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (459.79, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (479, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (690, 14, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3190.90, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (469, 17, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2300, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3589, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9000, 4, 6);